using Microsoft.UI.Xaml.Controls;

namespace WinTools;

public sealed partial class MainWindow
{
    private Border AssocEditPanel => FeaturePages.GetControl<Border>(nameof(AssocEditPanel));
    private Border ImeEditPanel => FeaturePages.GetControl<Border>(nameof(ImeEditPanel));
    private Button ThreeFingerCalibrateButton => FeaturePages.GetControl<Button>(nameof(ThreeFingerCalibrateButton));
    private ColumnDefinition AssocEditColumn => FeaturePages.GetControl<ColumnDefinition>(nameof(AssocEditColumn));
    private ColumnDefinition ImeEditColumn => FeaturePages.GetControl<ColumnDefinition>(nameof(ImeEditColumn));
    private ComboBox ImeAppComboBox => FeaturePages.GetControl<ComboBox>(nameof(ImeAppComboBox));
    private ComboBox ImeModeComboBox => FeaturePages.GetControl<ComboBox>(nameof(ImeModeComboBox));
    private Grid ContentDesktopOrganize => FeaturePages.GetControl<Grid>(nameof(ContentDesktopOrganize));
    private Grid ContentPerAppIme => FeaturePages.GetControl<Grid>(nameof(ContentPerAppIme));
    private Grid ContentProgramAssociation => FeaturePages.GetControl<Grid>(nameof(ContentProgramAssociation));
    private ListView AssocListView => FeaturePages.GetControl<ListView>(nameof(AssocListView));
    private ListView ImeRulesListView => FeaturePages.GetControl<ListView>(nameof(ImeRulesListView));
    private ListView ZonesListView => FeaturePages.GetControl<ListView>(nameof(ZonesListView));
    private NumberBox DesktopCardGapBox => FeaturePages.GetControl<NumberBox>(nameof(DesktopCardGapBox));
    private NumberBox DesktopCardMarginBox => FeaturePages.GetControl<NumberBox>(nameof(DesktopCardMarginBox));
    private NumberBox DesktopCardMaxColumnsBox => FeaturePages.GetControl<NumberBox>(nameof(DesktopCardMaxColumnsBox));
    private NumberBox StashOffsetXBox => FeaturePages.GetControl<NumberBox>(nameof(StashOffsetXBox));
    private NumberBox StashOffsetYBox => FeaturePages.GetControl<NumberBox>(nameof(StashOffsetYBox));
    private ProgressBar ThreeFingerCalibrationProgress => FeaturePages.GetControl<ProgressBar>(nameof(ThreeFingerCalibrationProgress));
    private RadioButton ThemeRadioDark => FeaturePages.GetControl<RadioButton>(nameof(ThemeRadioDark));
    private RadioButton ThemeRadioLight => FeaturePages.GetControl<RadioButton>(nameof(ThemeRadioLight));
    private RadioButton ThemeRadioSystem => FeaturePages.GetControl<RadioButton>(nameof(ThemeRadioSystem));
    private RadioButtons ThemeRadioButtons => FeaturePages.GetControl<RadioButtons>(nameof(ThemeRadioButtons));
    private Grid ContentAppSettings => FeaturePages.GetControl<Grid>(nameof(ContentAppSettings));
    private Grid ContentDesktopClick => FeaturePages.GetControl<Grid>(nameof(ContentDesktopClick));
    private Grid ContentSpotlight => FeaturePages.GetControl<Grid>(nameof(ContentSpotlight));
    private Grid ContentDragStash => FeaturePages.GetControl<Grid>(nameof(ContentDragStash));
    private Grid ContentThreeFingerDrag => FeaturePages.GetControl<Grid>(nameof(ContentThreeFingerDrag));
    private TextBlock AssocCountText => FeaturePages.GetControl<TextBlock>(nameof(AssocCountText));
    private TextBlock AssocEmptyHint => FeaturePages.GetControl<TextBlock>(nameof(AssocEmptyHint));
    private TextBlock ImeEmptyHint => FeaturePages.GetControl<TextBlock>(nameof(ImeEmptyHint));
    private TextBlock ZoneEmptyHint => FeaturePages.GetControl<TextBlock>(nameof(ZoneEmptyHint));
    private TextBlock CollectStatusText => FeaturePages.GetControl<TextBlock>(nameof(CollectStatusText));
    private TextBlock AssocEditTitle => FeaturePages.GetControl<TextBlock>(nameof(AssocEditTitle));
    private TextBlock ImeCountText => FeaturePages.GetControl<TextBlock>(nameof(ImeCountText));
    private TextBlock ThreeFingerCalibrationStatusText => FeaturePages.GetControl<TextBlock>(nameof(ThreeFingerCalibrationStatusText));
    private TextBlock ZoneCountText => FeaturePages.GetControl<TextBlock>(nameof(ZoneCountText));
    private TextBox AssocExtBox => FeaturePages.GetControl<TextBox>(nameof(AssocExtBox));
    private TextBox AssocNameBox => FeaturePages.GetControl<TextBox>(nameof(AssocNameBox));
    private TextBox AssocPathBox => FeaturePages.GetControl<TextBox>(nameof(AssocPathBox));
    private TextBox HotkeyDesktopCardBox => FeaturePages.GetControl<TextBox>(nameof(HotkeyDesktopCardBox));
    private ToggleSwitch DesktopCardToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(DesktopCardToggle));
    private ToggleSwitch AutoStartToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(AutoStartToggle));
    private ToggleSwitch DesktopClickToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(DesktopClickToggle));
    private ToggleSwitch DragStashToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(DragStashToggle));
    private ToggleSwitch PerAppImeToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(PerAppImeToggle));
    private ToggleSwitch ProgramAssocToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(ProgramAssocToggle));
    private ToggleSwitch ThreeFingerDragToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(ThreeFingerDragToggle));
    private ToggleSwitch SpotlightToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(SpotlightToggle));
    private TextBox HotkeySpotlightBox => FeaturePages.GetControl<TextBox>(nameof(HotkeySpotlightBox));
    private TextBlock SpotlightStatusText => FeaturePages.GetControl<TextBlock>(nameof(SpotlightStatusText));
    private Grid ContentVoiceBall => FeaturePages.GetControl<Grid>(nameof(ContentVoiceBall));
    private ToggleSwitch VoiceBallToggle => FeaturePages.GetControl<ToggleSwitch>(nameof(VoiceBallToggle));
    private TextBox HotkeyVoiceBallBox => FeaturePages.GetControl<TextBox>(nameof(HotkeyVoiceBallBox));
    private CommunityToolkit.WinUI.Controls.SettingsCard VoiceBallHotkeyCard => FeaturePages.GetControl<CommunityToolkit.WinUI.Controls.SettingsCard>(nameof(VoiceBallHotkeyCard));
    private CommunityToolkit.WinUI.Controls.SettingsCard VoiceBallPositionCard => FeaturePages.GetControl<CommunityToolkit.WinUI.Controls.SettingsCard>(nameof(VoiceBallPositionCard));
    private Button VoiceBallResetPositionButton => FeaturePages.GetControl<Button>(nameof(VoiceBallResetPositionButton));
}
